#!/usr/bin/env python
"""Generate a minimal test export bundle for YouTube uploader testing.

Creates a simple test video + metadata structure at exports/test-project/
suitable for testing the youtube_uploader.py CLI without running a full pipeline.

Usage:
  python tools/publish/create_test_bundle.py [--output exports/test-project]
"""
import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def create_test_video(output_path: str, duration: int = 10) -> bool:
    """Create a minimal test MP4 using ffmpeg."""
    try:
        # Simple 1080p test video with color (no filters to maximize compatibility)
        cmd = [
            "ffmpeg",
            "-f", "lavfi",
            "-i", f"color=c=blue:s=1920x1080:d={duration}",
            "-pix_fmt", "yuv420p",
            "-c:v", "libx264",
            "-preset", "ultrafast",
            "-y",
            output_path
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            print(f"ffmpeg error: {result.stderr}")
            return False
        print(f"Created test video: {output_path}")
        return True
    except FileNotFoundError:
        print("ERROR: ffmpeg not found. Install ffmpeg to generate test videos.")
        return False
    except Exception as e:
        print(f"ERROR creating video: {e}")
        return False


def create_metadata(export_path: str) -> bool:
    """Create minimal metadata.json for the export bundle."""
    metadata = {
        "title": "OpenMontage YouTube Uploader Test",
        "description": "This is a test video generated by OpenMontage's youtube_uploader test suite. "
                       "It demonstrates the end-to-end workflow: pipeline → export → upload.",
        "tags": ["openmontage", "test", "youtube-api"],
        "chapters": [
            {"start_seconds": 0, "title": "Test Video"}
        ],
        "generated_at": datetime.now().isoformat(),
        "pipeline": "test-bundle",
        "version": "1.0"
    }
    
    metadata_dir = Path(export_path) / "metadata"
    metadata_dir.mkdir(parents=True, exist_ok=True)
    
    metadata_file = metadata_dir / "metadata.json"
    with open(metadata_file, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)
    
    print(f"Created metadata: {metadata_file}")
    
    # Also create description.txt
    description_file = metadata_dir / "description.txt"
    with open(description_file, "w", encoding="utf-8") as f:
        f.write(metadata["description"])
    
    # Create tags.txt
    tags_file = metadata_dir / "tags.txt"
    with open(tags_file, "w", encoding="utf-8") as f:
        f.write("\n".join(metadata["tags"]))
    
    return True


def create_test_bundle(output_base: str = "exports/test-project") -> bool:
    """Create a complete test export bundle."""
    export_path = Path(output_base)
    video_dir = export_path / "video"
    video_dir.mkdir(parents=True, exist_ok=True)
    
    video_file = video_dir / "test_video.mp4"
    
    # Create test video
    if not create_test_video(str(video_file), duration=5):
        return False
    
    # Create metadata
    if not create_metadata(str(export_path)):
        return False
    
    # Create a placeholder thumbnail concept
    thumbnail_dir = export_path / "thumbnails"
    thumbnail_dir.mkdir(parents=True, exist_ok=True)
    
    concept_file = thumbnail_dir / "concept.json"
    with open(concept_file, "w", encoding="utf-8") as f:
        json.dump({
            "text_overlay": "OpenMontage Test",
            "style_notes": "Blue background with white text"
        }, f, indent=2)
    
    print(f"\n✓ Test export bundle created at: {export_path}")
    print(f"  - Video: {video_file}")
    print(f"  - Metadata: {export_path / 'metadata' / 'metadata.json'}")
    print(f"  - Thumbnail concept: {concept_file}")
    print(f"\nReady to upload. Run:")
    print(f"  python tools/publish/youtube_uploader.py --export-path {export_path} --client-secrets /path/to/client_secrets.json --privacy private")
    
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate a minimal test export bundle for youtube_uploader")
    parser.add_argument("--output", default="exports/test-project", help="Output directory for the export bundle")
    args = parser.parse_args()
    
    if not create_test_bundle(args.output):
        sys.exit(1)


if __name__ == "__main__":
    main()
